"""Python script for running a series of exciting calculations."""

import os
from argparse import ArgumentParser
from pathlib import Path

from excitingscripts.execute.single import run_exciting


def run_optimize_lattice(run_dir: Path) -> None:
    """Run a series of exciting calculations with different volumes generated by the script
    'excitingscripts.optimize.setup'.

    :param run_dir: Directory where exciting runs.
    """
    if not run_dir.exists():
        raise FileNotFoundError(f"Directory {run_dir} not found.")

    dir_prefix = run_dir.stem.lower()
    listdir = os.listdir(run_dir)
    displ_points = len(listdir)

    for directory in listdir:
        if not directory.startswith(f"{dir_prefix}_") or not directory[-1].isdigit():
            displ_points -= 1

    for i in range(displ_points):
        root_directory = run_dir / f"{dir_prefix}_{i + 1}"
        filename = "input.xml"
        run_exciting(root_directory=root_directory, filename=filename)


def main() -> None:
    parser = ArgumentParser(
        description="Python script for running a series of exciting calculations."
    )

    parser.add_argument(
        "-d",
        "--directory",
        type=str,
        default=Path.cwd(),
        help="Directory where exciting runs",
    )

    args = parser.parse_args()
    run_dir = Path(args.directory)

    run_optimize_lattice(run_dir)


if __name__ == "__main__":
    main()
