#! /bin/sh

# list of files with file containing header as first one
mainfile="xsmain.F90"
restoffiles="`/bin/ls -A1 *.F90 | grep -v xsmain`"
files="$mainfile $restoffiles"
texfile=xs.tex

echo
echo "Processing the following files for protex-documentation......."
echo
echo $files
echo

# invoke protex
../protex -s $files > $texfile

# invoke latex
cmd="latex $texfile"
$cmd && $cmd && $cmd

echo
echo "done"
echo
