[metadata]
name = excitingjupyter
version = 0.0.2

[options]
packages = excitingjupyter
install_requires =
    requests
    excitingtools >= 1.1.0
    ase >= 3.20.0
    notebook == 7.0.0 
    jupyterlab-widgets == 3.0.0
    ipywidgets == 8.0.0
    widgetsnbextension == 4.0.0
    nglview == 3.1.4
    nbformat >= 5.0.0
