#!/bin/csh
if ( $#argv == 0 || x"$1" == "x-h" ) then
  cat - <<EOF
Syntax: ezmpirun node1,node2,... command param
EOF
  exit
endif

echo -n "" >! machlist.in
foreach mach (`echo $1 | sed 's/,/ /g'`)
  echo $mach >> machlist.in
end
mpirun -nolocal -np `echo $1 | sed 's/,/ /g' | wc -w` -machinefile machlist.in `which $2` $argv[3-]
