# Top-level Gitlab Continuous Integration Config File for exciting

# Notice Cray CI is deactivated as it requires of extra permissions

stages:
  - python
  - build
  - test
  - deploy

# Split configurations into separate files
include:
  - local: '/.gitlab/python-libs.yml'
  - local: '/.gitlab/docs.yml'
  - local: '/.gitlab/jupyter-exciting-python3-gnu-smp.yml'
  - local: '/.gitlab/exciting-fedora-buster-gnu-serial.yml'
  - local: '/.gitlab/exciting-fedora-buster-gnu-smp.yml'
  - local: '/.gitlab/exciting-fedora-buster-gnu-mpismp.yml'
  - local: '/.gitlab/exciting-fedora-buster-gnu-mpismp-scalapack-hdf5.yml'
  - local: '/.gitlab/exciting-debian-buster-intel2021-serial.yml'
  - local: '/.gitlab/exciting-debian-buster-intel2021-smp.yml'
  - local: '/.gitlab/exciting-debian-buster-intel2025-serial.yml'
  - local: '/.gitlab/exciting-debian-buster-intel2025-gpu.yml'
  - local: '/.gitlab/python-libs-amdgpu.yml'
  - local: '/.gitlab/exciting-cray-amdgpu.yml'
  - local: '/.gitlab/exciting-llvm-amdgpu.yml'
