"""
Module containing default tolerances for ground state output.

All unique {keys:tolerances} for ground state outputs.
Each entry has a unique key and value = {'tolerance':value, 'unit':Unit.unit}
where Unit is an enum class.  If a quantity does not have an associated unit,
unit = null.

Keys were generated by using the tolerance.py script. See that for command line details.

Tolerances in default_tolerances cover files:
  * PHONON.OUT
"""
from excitingtools import Unit

# currentdir = os.path.dirname(os.path.realpath(__file__))
# parentdir = os.path.dirname(currentdir)
# sys.path.append(os.path.dirname(parentdir))
#
# from tolerance.tol_classes import DefaultTolerances, Tol, TolWithMessage

from ..tol_classes import DefaultTolerances, Tol, TolWithMessage

# Default phonon tolerances
default = DefaultTolerances(integer=Tol(0),
                            float=Tol(1.e-8),
                            str=Tol(''),
                            frequency=Tol(2.e-8, Unit.hartree),
                            )


# PHONON.OUT
phonons_out = {'frequency': default.frequency}

# Single dictionary for all tested ground state outputs, for dumping to JSON
phonons_tolerances = {'PHONON.OUT': phonons_out}
