"""
Module containing default tolerances for phonon output.

All unique {keys:tolerances} for phonon outputs.
Each entry has a unique key and value = {'tolerance':value, 'unit':Unit.unit}
where Unit is an enum class.  If a quantity does not have an associated unit,
'unit = None.

Keys were generated by using the tolerance.py script. See that for command line
details.

Tolerances in default_tolerances cover files:
  * DYN_Q??.OUT
  * PHONON.OUT
  * EPSINF.OUT
  * ZSTAR.OUT
"""
from excitingtools import Unit

from ..tol_classes import DefaultTolerances, Tol, TolWithMessage

default = DefaultTolerances(integer=Tol(0),
                            float=Tol(1.e-6),
                            length=Tol(1.e-4, Unit.bohr),
                            energy=Tol(1.e-6, Unit.hartree)
                            )

# DYN_Q??.OUT file
dyn = {
        'species': default.integer,
        'atom': default.integer,
        'polarisation': default.integer,
        'dynmat_real': default.float,
        'dynmat_imag': default.float
        }

# PHONON.OUT file
phonon = {
        'q_vector': default.float,
        'mode_index': default.integer,
        'frequency': default.energy,
        'species': default.integer,
        'atom': default.integer,
        'polarisation': default.integer
        }

# EPSINF.OUT file
epsinf = {
        'epsinf': default.float
        }

# ZSTAR.OUT file
zstar = {
        'species': default.integer,
        'atom': default.integer,
        'position': default.float,
        'tensor': default.float
        }

# Single dictionary for all tested Wannier outputs, for dumping to JSON
phonon_tolerances = {
        'DYN_Q??.OUT': dyn,
        'PHONON.OUT': phonon,
        'EPSINF.OUT': epsinf,
        'ZSTAR.OUT': zstar
        }
