<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ex="http://xml.exciting-code.org/inputschemaextentions.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xsi:schemaLocation="http://xml.exciting-code.org/inputschemaextentions.xsd    http://xml.exciting-code.org/inputschemaextentions.xsd">
  <xs:include id="common" schemaLocation="common.xsd"/>
  <xs:annotation>
    <xs:appinfo>
        <parent>/input</parent>
        <root>eph</root>
    </xs:appinfo>
  </xs:annotation>
  <xs:element ex:importance="essential" ex:unit="" name="eph">
    <xs:annotation>
        <xs:documentation>Electron-phonon calculation setup.</xs:documentation>
    </xs:annotation>

    <xs:complexType>

      <xs:all>

<!-- ******************************************************************************** -->
<!-- ELECTRON-PHONON MATRIX ELEMENTS -->
        <xs:element ex:importance="essential" ex:unit="" name="ephmat" maxOccurs="1" minOccurs="0">
          <xs:annotation>
            <xs:documentation>
              Settings for calculation of electron-phonon matrix elements.
            </xs:documentation>
          </xs:annotation>

          <xs:complexType>

            <xs:attribute ex:importance="essential" ex:unit="" name="do" default="fromscratch">
              <xs:annotation>
                <xs:documentation>
                  Decides if the matrix elements are (re)computed from scratch or if the calculation is skipped.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="fromscratch"/>
                  <xs:enumeration value="skip"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="standard" type="xs:boolean" default="true">
              <xs:annotation>
                <xs:documentation>
                  Compute standard electron-phonon matrix elements.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="hilo" type="xs:boolean" default="true">
              <xs:annotation>
                <xs:documentation>
                  Compute effective high and low (hilo) energy matrix elements for self-energy calculation.
                  They are used to approximate the contributions to the self-energy from bands outside the
                  Wannierized part of the bandstructure.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            
            <xs:attribute ex:importance="experimental" ex:unit="" name="debye_waller" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>
                  Compute matrix elements used in operator formulation of the Debye-Waller self-energy.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
      
          </xs:complexType>

        </xs:element>
<!-- ................................................................................ -->

<!-- ******************************************************************************** -->
<!-- ELECTRON ENERGY INTERPOLATION -->
        <xs:element ex:importance="expert" ex:unit="" name="el_interpolation" maxOccurs="1" minOccurs="0">
          <xs:annotation>
            <xs:documentation>
              Interpolate electron energies on target set and write result to file.
            </xs:documentation>
          </xs:annotation>

          <xs:complexType>
      
            <xs:attribute ex:importance="expert" ex:unit="" name="format" default="text">
              <xs:annotation>
                <xs:documentation>
                  Output format. Choose from plain <pre>text</pre> or <pre>json</pre>.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="text"/>
                  <xs:enumeration value="json"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>

          </xs:complexType>

        </xs:element>
<!-- ................................................................................ -->

<!-- ******************************************************************************** -->
<!-- PHONON FREQUENCY INTERPOLATION -->
        <xs:element ex:importance="expert" ex:unit="" name="ph_interpolation" maxOccurs="1" minOccurs="0">
          <xs:annotation>
            <xs:documentation>
              Interpolate phonon frequencies on target set and write result to file.
            </xs:documentation>
          </xs:annotation>

          <xs:complexType>
      
            <xs:attribute ex:importance="expert" ex:unit="" name="format" default="text">
              <xs:annotation>
                <xs:documentation>
                  Output format. Choose from plain <pre>text</pre> or <pre>json</pre>.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="text"/>
                  <xs:enumeration value="json"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>

          </xs:complexType>

        </xs:element>
<!-- ................................................................................ -->

<!-- ******************************************************************************** -->
<!-- EPH MATRIX INTERPOLATION -->
        <xs:element ex:importance="expert" ex:unit="" name="eph_interpolation" maxOccurs="1" minOccurs="0">
          <xs:annotation>
            <xs:documentation>
              Interpolate electron-phonon matrix elements on target set and write result to file.
            </xs:documentation>
          </xs:annotation>

          <xs:complexType>
      
            <xs:attribute ex:importance="expert" ex:unit="" name="format" default="text">
              <xs:annotation>
                <xs:documentation>
                  Output format. Choose from plain <pre>text</pre> or <pre>json</pre>.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="text"/>
                  <xs:enumeration value="json"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
      
            <xs:attribute ex:importance="essential" ex:unit="" name="fix" default="k">
              <xs:annotation>
                <xs:documentation>
                  Choose whether to fix electron momentum <inlinemath>{\mathbf k}</inlinemath> or phonon momentum <inlinemath>{\mathbf q}</inlinemath>.
                  The other will be taken from the target set.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="k"/>
                  <xs:enumeration value="q"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>

            <xs:attribute ex:importance="essential" ex:unit="" name="vplfix" type="vect3d" default="0.0d0 0.0d0 0.0d0">
              <xs:annotation>
                <xs:documentation>
                  Fixed momentum vector in lattice coordinates.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="include_polar" type="xs:boolean" default="true">
              <xs:annotation>
                <xs:documentation>
                  Include long-range polar Fröhlich coupling in polar materials.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

          </xs:complexType>

        </xs:element>
<!-- ................................................................................ -->

<!-- ******************************************************************************** -->
<!-- ELECTRON SELF-ENERGY -->
        <xs:element ex:importance="expert" ex:unit="" name="el_self_energy" maxOccurs="1" minOccurs="0">
          <xs:annotation>
            <xs:documentation>
              Settings for calculation of electron self-energy.
            </xs:documentation>
          </xs:annotation>

          <xs:complexType>

            <xs:all>

              <xs:element ex:importance="expert" ex:unit="" ref="freq_grid" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                  <xs:documentation>
                    Frequency grid on which self-energy is computed.
                  </xs:documentation>
                </xs:annotation>
              </xs:element>

              <xs:element ex:importance="expert" ex:unit="" name="output_settings" maxOccurs="1" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>
                    Settings for human-readable output of electron self-energy and spectral function.
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:all>
                    <xs:element ex:importance="expert" ex:unit="" ref="freq_grid" minOccurs="0" maxOccurs="1">
                      <xs:annotation>
                        <xs:documentation>
                          Frequency grid.
                        </xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:all>
                  <xs:attribute ex:importance="expert" ex:unit="" name="directory" type="xs:string" default="auto">
                    <xs:annotation>
                      <xs:documentation>
                        Name of directory to save human-readable output in. If 'auto', the name will be generated automatically from the used calculation parameters.
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute ex:importance="expert" ex:unit="" name="interpolation_method" default="spline">
                    <xs:annotation>
                      <xs:documentation>
                        Method used for interpolating self-energy on output grid.
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="spline"/>
                        <xs:enumeration value="linear"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute ex:importance="expert" ex:unit="" name="format" default="text">
                    <xs:annotation>
                      <xs:documentation>
                        Output format. Choose from plain <pre>text</pre> or <pre>json</pre>.
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="text"/>
                        <xs:enumeration value="json"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>

            </xs:all>

            <xs:attribute ex:importance="essential" ex:unit="" name="do" default="fromscratch">
              <xs:annotation>
                <xs:documentation>
                  Decides if the self energy is (re)computed from scratch, read from file or if the calculation is skipped.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="fromscratch"/>
                  <xs:enumeration value="fromfile"/>
                  <xs:enumeration value="skip"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="Kelvin" name="tempset" type="vect3d" default="0.0d0 0.0d0 0.0d0">
              <xs:annotation>
                <xs:documentation>
                  Temperature set for which to calculate self-energy. Given as lower bound, upper bound, step.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            
            <xs:attribute ex:importance="essential" ex:unit="" name="ngridbz" type="integertriple" default="2 2 2">
              <xs:annotation>
                <xs:documentation>
                  <inlinemath>{\mathbf q}</inlinemath>-point grid used for Brillouin zone integration.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            
            <xs:attribute ex:importance="essential" ex:unit="" name="vbzoff" type="vect3d" default="0.0d0 0.0d0 0.0d0">
              <xs:annotation>
                <xs:documentation>
                  The <inlinemath>{\mathbf q}</inlinemath>-point offset vector for integration grid in lattice coordinates.
                  It is recommended to shift the grid in polar materials to avoid Gamma point sampling.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
      
            <xs:attribute ex:importance="essential" ex:unit="" name="integration" default="kramers-kronig">
              <xs:annotation>
                <xs:documentation>
                  Integration method for BZ integral.<br/>
                  <pre>kramers-kronig</pre>: Use tetrahedron integration for the imaginary part of the self-energy and obtain real part from Kramers-Kronig relation.<br/>
                  <pre>smearing</pre>: Use imaginary smearing (eta) (see <pre>swidth</pre>).
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="smearing"/>
                  <xs:enumeration value="kramers-kronig"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
      
            <xs:attribute ex:importance="expert" ex:unit="Hartree" name="swidth" type="fortrandouble" default="0.001">
              <xs:annotation>
                <xs:documentation>
                  Smearing width (eta). For tetrahedron integration an artificial Lorentzian broadening with this width is applied.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="nfreqperband" type="xs:integer" default="20">
              <xs:annotation>
                <xs:documentation>
                  Number of frequency points per band. May be overwritten, if element <pre>freq_grid</pre> is present.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" type="xs:integer" ex:unit="" name="eqpsolver" default="1">
              <xs:annotation>
                <xs:documentation>
                  Schemes to solve the quasiparticle (non-linear) equation:
                  <list>
                    <li>0 - on-the-mass-shell approximation</li>
                    <li>1 - real perturbative</li>
                    <li>2 - complex perturbative</li>
                    <li>3 - iterative</li>
                  </list>
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

          </xs:complexType>

        </xs:element>
<!-- ................................................................................ -->

<!-- ******************************************************************************** -->
<!-- ELECTRON-PHONON COUPLING STRENGTH -->
        <xs:element ex:importance="expert" ex:unit="" name="coupling_strength" maxOccurs="1" minOccurs="0">
          <xs:annotation>
            <xs:documentation>
              Settings for calculation of EPH coupling strength.
            </xs:documentation>
          </xs:annotation>

          <xs:complexType>

            <xs:all>

               <xs:element ex:importance="expert" ex:unit="" ref="freq_grid" minOccurs="0" maxOccurs="1">
                 <xs:annotation>
                   <xs:documentation>
                     Frequency grid on which integrated coupling strength is computed.
                   </xs:documentation>
                 </xs:annotation>
               </xs:element>

            </xs:all>

            <xs:attribute ex:importance="essential" ex:unit="" name="particle" default="phonon">
              <xs:annotation>
                <xs:documentation>
                  Decides if the coupling strength is computed electron/hole or phonon resolved.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="electron"/>
                  <xs:enumeration value="phonon"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>

            <xs:attribute ex:importance="essential" ex:unit="" name="do" default="fromscratch">
              <xs:annotation>
                <xs:documentation>
                  Decides if the coupling strength is (re)computed from scratch or if the calculation is skipped.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="fromscratch"/>
                  <xs:enumeration value="skip"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="quasielastic" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>
                  Use quasielastic approximation, i.e., don't distinguish between phonon absorption and emission.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
      
            <xs:attribute ex:importance="expert" ex:unit="" name="integrated" type="xs:boolean" default="false">
              <xs:annotation>
                <xs:documentation>
                  Calculated coupling strength integrated over BZ.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="format" default="text">
              <xs:annotation>
                <xs:documentation>
                  Output format. Choose from plain <pre>text</pre> or <pre>json</pre>.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="text"/>
                  <xs:enumeration value="json"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="nfreqint" type="xs:integer" default="1000">
              <xs:annotation>
                <xs:documentation>
                  Number of electron/phonon frequencies for integrated coupling strength.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="nfreqa2F" type="xs:integer" default="300">
              <xs:annotation>
                <xs:documentation>
                  Number of phonon frequencies for integration of Eliashberg function.
                  (Applies to <pre>particle='electron'</pre> only.)
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="Hartree" name="energy" type="fortrandouble" default="0.0">
              <xs:annotation>
                <xs:documentation>
                  Electron energy at which phonon coupling strength is evaluated. Relative to Fermi energy.
                  (Applies to <pre>particle='phonon'</pre> only.)
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="cm^-3" name="doping" type="fortrandouble" default="0.0">
              <xs:annotation>
                <xs:documentation>
                  Doping concentration (in 1/cm^3) for which phonon coupling strength is evaluated.
                  Positive for electron/donor doping. Negative for hole/acceptor doping.
                  Outrules attribute <pre>energy</pre>.
                  (Applies to <pre>particle='phonon'</pre> only.)
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="parmode" default="points">
              <xs:annotation>
                <xs:documentation>
                  Parallelization mode. 
                  <pre>points</pre> for parallelization of target points (higher efficiency).
                  <pre>bands</pre> for parallelization of electron and phonon bands (lower memory).
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="points"/>
                  <xs:enumeration value="bands"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
      
            <!-- k-grid -->
            <xs:attribute ex:importance="essential" ex:unit="" name="ngridk" type="integertriple" default="2 2 2">
              <xs:annotation>
                <xs:documentation>
                  <inlinemath>{\mathbf k}</inlinemath>-point grid used for Brillouin zone integration over electron momentum.
                  No effect if <pre>integrated='false'</pre> and <pre>particle='electron'</pre>.
                  <pre>target</pre> is used as <inlinemath>{\mathbf k}</inlinemath>-point set instead.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute ex:importance="essential" ex:unit="" name="vkloff" type="vect3d" default="0.0d0 0.0d0 0.0d0">
              <xs:annotation>
                <xs:documentation>
                  The <inlinemath>{\mathbf k}</inlinemath>-point offset vector for integration grid in lattice coordinates.
                  It is recommended to shift the grid, if <pre>particle='phonon'</pre>.
                  No effect if <pre>integrated='false'</pre> and <pre>particle='electron'</pre>.
                  <pre>target</pre> is used as <inlinemath>{\mathbf k}</inlinemath>-point set instead.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute ex:importance="expert" ex:unit="" name="reducek" type="xs:boolean" default="true">
              <xs:annotation>
                <xs:documentation>
	          Flag to specify whether the <inlinemath>{\mathbf k}</inlinemath>-point integration grid is reduced using symmetry operations.
                  No effect if <pre>integrated='false'</pre> and <pre>particle='electron'</pre>.
                  <pre>target</pre> is used as <inlinemath>{\mathbf k}</inlinemath>-point set instead.
	        </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <!-- q-grid -->
            <xs:attribute ex:importance="essential" ex:unit="" name="ngridq" type="integertriple" default="2 2 2">
              <xs:annotation>
                <xs:documentation>
                  <inlinemath>{\mathbf q}</inlinemath>-point grid used for Brillouin zone integration over phonon momentum.
                  No effect if <pre>integrated='false'</pre> and <pre>particle='phonon'</pre>.
                  <pre>target</pre> is used as <inlinemath>{\mathbf q}</inlinemath>-point set instead.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute ex:importance="essential" ex:unit="" name="vqloff" type="vect3d" default="0.0d0 0.0d0 0.0d0">
              <xs:annotation>
                <xs:documentation>
                  The <inlinemath>{\mathbf q}</inlinemath>-point offset vector for integration grid in lattice coordinates.
                  It is recommended to shift the grid, if <pre>particle='electron'</pre>.
                  No effect if <pre>integrated='false'</pre> and <pre>particle='phonon'</pre>.
                  <pre>target</pre> is used as <inlinemath>{\mathbf q}</inlinemath>-point set instead.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute ex:importance="expert" ex:unit="" name="reduceq" type="xs:boolean" default="true">
              <xs:annotation>
                <xs:documentation>
	          Flag to specify whether the <inlinemath>{\mathbf q}</inlinemath>-point integration grid is reduced using symmetry operations.
                  No effect if <pre>integrated='false'</pre> and <pre>particle='phonon'</pre>.
                  <pre>target</pre> is used as <inlinemath>{\mathbf q}</inlinemath>-point set instead.
	        </xs:documentation>
              </xs:annotation>
            </xs:attribute>

          </xs:complexType>

        </xs:element>
<!-- ................................................................................ -->

<!-- ******************************************************************************** -->
<!-- TARGET WAVE VECTORS -->
        <xs:element ex:importance="essential" ex:unit="" name="target" maxOccurs="1" minOccurs="0">
          <xs:annotation>
            <xs:documentation>
              Set of reciprocal space points <inlinemath>{\mathbf p}</inlinemath> for target quantities. 
              The meaning (electron or phonon wavevector) varies depending on the context. Can be a regular grid or a 1D path.
              If not present, the original <inlinemath>{\mathbf k}</inlinemath>- or <inlinemath>{\mathbf q}</inlinemath>-grid will be used.
            </xs:documentation>
          </xs:annotation>

          <xs:complexType>

            <xs:all>

              <xs:element ex:importance="expert" ex:unit="" ref="plot1d" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                  <xs:documentation>
                    Vertices specifying a path in the BZ.
                  </xs:documentation>
                </xs:annotation>
              </xs:element>

            </xs:all>

            <xs:attribute ex:importance="essential" ex:unit="" name="ngridp" type="integertriple" default="0 0 0">
              <xs:annotation>
                <xs:documentation>
                  Regular <inlinemath>{\mathbf p}</inlinemath>-point grid size.
                  If a target path is specified, this is ignored.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="vploff" type="vect3d" default="0.0d0 0.0d0 0.0d0">
              <xs:annotation>
                <xs:documentation>
                  Offset of the <inlinemath>{\mathbf p}</inlinemath>-point grid.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>

            <xs:attribute ex:importance="expert" ex:unit="" name="reducep" type="xs:boolean" default="true">
              <xs:annotation>
                <xs:documentation>
	           Flag to specify whether the <inlinemath>{\mathbf p}</inlinemath>-point grid is reduced using symmetry operations.
	        </xs:documentation>
              </xs:annotation>
            </xs:attribute>
        
          </xs:complexType>

        </xs:element>

      </xs:all>

<!-- ******************************************************************************** -->
<!-- GENERAL SETTINGS -->
      <xs:attribute ex:importance="expert" ex:unit="Hartree" name="efermi" type="fortrandouble" default="0.0">
        <xs:annotation>
          <xs:documentation>
            Fermi energy. Can be manually set to, e.g. VBM or CBm. Default: Automatic determination.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      
      <xs:attribute ex:importance="expert" ex:unit="Hartree" name="scissor" type="fortrandouble" default="0.0">
        <xs:annotation>
          <xs:documentation>
            Scissor operator to apply. See also <pre>scissor_direction</pre>.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>

      <xs:attribute ex:importance="expert" ex:unit="" name="scissor_direction" default="symmetric">
        <xs:annotation>
          <xs:documentation>
            Specify to apply scissor shift to occupied, unoccupied states or symmetrically to both.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="occupied"/>
            <xs:enumeration value="unoccupied"/>
            <xs:enumeration value="symmetric"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      
      <xs:attribute ex:importance="expert" ex:unit="" name="wfrange" type="integerpair" default="1 0">
        <xs:annotation>
          <xs:documentation>
            Lower and upper bound of Wannier functions to be included in EPH calculation. Default is all.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      
      <xs:attribute ex:importance="expert" ex:unit="" name="mindistel" type="xs:boolean" default="true">
        <xs:annotation>
          <xs:documentation>
            Apply minimal distance interpolation for electrons. This is more expensive but also more accurate for coarse support k-grids. Check effect before by running <pre>el_interpolation</pre>.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      
      <xs:attribute ex:importance="expert" ex:unit="" name="mindistph" type="xs:boolean" default="true">
        <xs:annotation>
          <xs:documentation>
            Apply minimal distance interpolation for phonons. This is more expensive but also more accurate for coarse support q-grids. Check effect before by running <pre>ph_interpolation</pre>.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
        
      <xs:attribute ex:importance="expert" ex:unit="Hartree" name="epsdegel" type="fortrandouble" default="1d-4">
        <xs:annotation>
          <xs:documentation>
            Maximum difference between electron energies to be considered degenerate.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>

      <xs:attribute ex:importance="expert" ex:unit="Hartree" name="epsdegph" type="fortrandouble" default="1d-5">
        <xs:annotation>
          <xs:documentation>
            Maximum difference between phonon energies to be considered degenerate.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>

      <xs:attribute ex:importance="expert" ex:unit="" name="elphbolt" type="xs:boolean" default="false">
        <xs:annotation>
          <xs:documentation>
             Run compatible with `elphbolt` code, i.e., use elphbolt compatible non-analytic dynamical matrix.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
<!-- ................................................................................ -->
        
    </xs:complexType>
  </xs:element>
</xs:schema>
