wiki/*: *.xsd
	xsltproc ../schematowikidot.xsl input.xsd >wiki/input;\
	xsltproc ../schematowikidot.xsl structure.xsd >wiki/structure;\
	xsltproc ../schematowikidot.xsl groundstate.xsd >wiki/groundstate;\
	xsltproc ../schematowikidot.xsl phonons.xsd >wiki/phonons;\
	xsltproc ../schematowikidot.xsl properties.xsd >wiki/properties;\
	xsltproc ../schematowikidot.xsl structureoptimization.xsd > wiki/structureoptimization;\
	xsltproc ../schematowikidot.xsl xs.xsd >wiki/xs;\
	xsltproc ../schematowikidot.xsl common.xsd >wiki/common