#!/bin/csh
set thereiserr=0

if (-e exciting.out) then
  foreach errmsg ( "Error")
    grep -i -q $errmsg exciting.out
    if ( $status == 0 ) then
      set thereiserr=1
    endif
  end
endif


if ( $thereiserr == 1 && x$1 == "x-e" ) then
  touch error
endif

if ( $thereiserr == 1 && x$1 == "x-p" ) then
  echo Error in `pwd`
endif

exit $thereiserr
