#!/usr/bin/tcsh

if ( ! -e ~/.ezexciting.rc ) then
cat - >! ~/.ezexciting.rc <<EOF
#!/usr/bin/tcsh
#enter name of exciting executable here
set excitingCMD="excitingser"
EOF
cat - <<EOF

===========================================================================
A default ~/.ezexciting.rc configuration file has been created for you.
===========================================================================

EOF
exit
else
  source ~/.ezexciting.rc
endif

if ( $#argv == 0 ) then
  echo "Syntax: ezexciting [-options] _file"
  echo "-h: help"
  echo "-n: do not run exciting"
  echo "-p: specifies the exciting command (default: excitingser)"
  exit 1
endif

foreach option ( $* )
  if (x$1 == "x-p") then
    shift
    set excitingCMD="$1"
    shift
  endif
  if (x$1 == "x-h") then
cat - <<EOF

==================================================================

Syntax: ezexciting [-n] [-p "..."] input_file

-n: do Not run exciting, but just create the input files.

-p: name of the exciting command ("excitingser" by default). 
    You can include an additional prefix such as:
    ezexciting -p "$EXCITINGROOT/bin/excitingser" input.xml

==================================================================

Here is an example of exciting.wrap file:

===== BEGIN OF EXAMPLE for the "exciting.wrap" file ==============
kppra = 512 # no. of k-points per reciprocal atom ... 512=8^3

___EXCITINGINPUT-BEGIN___
<input>
  <title>Al</title>
  <structure speciespath="$EXCITINGROOT/species/">
___CRYSTAL_AND_SPECIES___
  </structure>
  <groundstate ngridk="1 1 1" 
  nktot=___NKTOT___ mixer="msec"
  xctype="GGAPerdew-Burke-Ernzerhof"
  nwrite="1"
  dlinengyfermi="-0.1"
  fermilinengy="true"
  findlinentype="advanced"
  ></groundstate>
</input>

___EXCITINGINPUT-END___

===== END OF EXAMPLE =============================================

Note that the new token "kppra" has been introduced. It stands for 
"K-Point Per Reciprocal Atom". 
It is a way to automatically set the k-point mesh for a number of 
similar systems. Here is how it works: If you know that you need 
512 k-points for a 1-atom structure, then you type in 512. If
you now try calculate a similar structure with 2 atoms, the code
automatically uses 256 k-points. The mesh along the three axes is
automatically chosen to make the mesh as uniform as possible.

==================================================================

EOF
    exit 1
  endif
  if (x$1 == "x-n") then
    set norun
    shift
  endif
  if (x$1 == "x-d") then
    set debug
    shift
  endif
end

if (! -e $1) then
  echo Cannot open $1
  exit
endif

if (! $?norun ) then
  echo "ezexciting: Executing $excitingCMD ..."
  $excitingCMD >&! exciting.out
endif
