#!/usr/bin/tcsh 
# Syntax: str2ezexciting

set bin = $0:h

set wrapfilename="exciting.wrap"
if ( $#argv != 0 ) then
  set wrapfilename="$1"
endif

set strout="str_hint.out"

if ( ! -e $strout ) then
  set strout="str.out"
endif


if (! -e $strout ) then
  echo str.out or str_hint.out does not exist
  echo NOTE: str2ezexciting needs to be run within the subdirectory containing a structure.
  exit 1
endif

set str_vegard = $strout"_vegard"

#echo "strezexciting: Generating $str_vegard using $bin/apply_vegard.csh ..."

$bin/apply_vegard.csh > $str_vegard
awk 'NR>3' $strout >> $str_vegard


set wrapfile="$wrapfilename"
if (! -e $wrapfile) then
  set wrapfile="../$wrapfilename"
  if (! -e $wrapfile) then
    set wrapfile="../../$wrapfilename"
    if (! -e $wrapfile) then
      set wrapfile="../../../$wrapfilename"
      if (! -e $wrapfile) then
        echo You need a $wrapfilename file in $PWD , $PWD/.. , $PWD/../.. or $PWD/../../..
        echo NOTE: str2ezexciting needs to be run within the numbered subdirectory.
        exit 1
      endif
    endif
  endif
endif


#jus0
#set Al_example = ` cd $EXCITINGROOT/examples/Al/; echo $cwd/input.xml` 



#set dumm = `echo $EXCITINGROOT | sed s/"\/"/"\\\/"/g`


#set kppra = `sed s/"[ \t]"//g exciting.wrap | awk -F'[=#]' '/kppra/{print $2}'` 

set natoms = `awk '$4 ~ /[a-zA-Z]/{i++};END{print i}' $str_vegard` 

set kppra = ` awk -F'[=#]' '/kppra/{print $2}' $wrapfile` 

set nktot = `echo $natoms $kppra | awk '{printf "%d\n", $2/$1+0.5 }'` 



cat $wrapfile | getlines -jbt ___EXCITINGINPUT-BEGIN___ ___CRYSTAL_AND_SPECIES___ 

$bin/str.out2exciting.awk $str_vegard 

cat $wrapfile | getlines -jbt ___CRYSTAL_AND_SPECIES___ ___EXCITINGINPUT-END___ | sed s/___NKTOT___/\"$nktot\"/

exit
