#! /bin/sh

st="-static"
exe=""
pre=""
mach=""
case `uname -s` in
Linux)	tag=Linux
	pre=linux32
	mach="-m32" ;;
Darwin)	tag=Mac
	st="-static-libgcc" ;;
CYG*)	tag=Windows
	exe=.exe ;;
esac

$pre ./configure CFLAGS="-O3 -fomit-frame-pointer -ffast-math $st $mach"

$pre make MCFLAGS=-st math

for file in Vegas Suave Divonne Cuhre ; do
  gzip $file$exe
  mv $file$exe.gz $file$exe-$tag.gz
done

