#! /bin/sh
cp="/bin/cp -f"
rm="/bin/rm -f"
mv="/bin/mv -f"
#githashhead=`cat ../../../.git/HEAD |awk '{print $2}'`
#githash=`cat ../../../.git/$githashhead`
githash=`awk -F '"' '{print $2}' < ../../../src/version.inc`
exec="../../../build/serial/exciting"

fileskeep="QPOINTS.OUT GQPOINTS_QMT*.OUT EPSILON_*.OUT LOSS_*.OUT SIGMA_*.OUT \
SUMRULES_*.OUT EIGVAL_QMT*.OUT XSINFO.OUT.*"

# check if source code has local modifications
localmods=""
if [ `git-diff | wc -l` -ne 0 ]; then
	echo "Warning: source code has local modifications"
	localmods=".modified"
fi
odir=$githash$localmods

# SCF calculation

echo "SCF calculation..."
$cp exciting.in.scf exciting.in
$exec
$rm exciting.in

# test with mdftype=0 (using eps^-1(0,0)(q+G0))

echo "EELS and dynamical structure factor. cf. Weissker, PRL 2006"
echo "EELS: Si, RPA calculation..."
$cp exciting.in.xs.1 exciting.in
$exec
$rm exciting.in
$mv XSINFO.OUT XSINFO.OUT.1

echo "EELS: Si, ALDA calculation..."
$cp exciting.in.xs.2 exciting.in
$exec
$rm exciting.in
$mv XSINFO.OUT XSINFO.OUT.2

echo "saving files for git hash id: $githash"
mkdir -p $odir
git-log -1 > $odir/git-lastlog.log
$cp $fileskeep $odir


echo "run finished"
