
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    
!! DO NOT EDIT                          !!  
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

! This file is automatically generated from the XML Schema
! all changes will be overwritten when anything changes in the Schema



module modspdb
use inputdom
implicit none

type atomicState_type
! Do not edit! This file is automatically generated from the XML Schema
 integer::n
 integer::l
 integer::kappa
 real(8)::occ
 logical::core
end type

type atomicState_type_array
type(atomicState_type),pointer::atomicState
 end type
    
type wf_type
! Do not edit! This file is automatically generated from the XML Schema
 real(8)::trialEnergy
 integer::matchingOrder
 logical::searchE
end type

type wf_type_array
type(wf_type),pointer::wf
 end type
    
type custom_type
! Do not edit! This file is automatically generated from the XML Schema
 integer::l
 character(512)::type
 real(8)::trialEnergy
 logical::searchE
  type(wf_type_array),pointer::wfarray(:)
end type

type custom_type_array
type(custom_type),pointer::custom
 end type
    
type lo_type
! Do not edit! This file is automatically generated from the XML Schema
 integer::l
  type(wf_type_array),pointer::wfarray(:)
end type

type lo_type_array
type(lo_type),pointer::lo
 end type
    
type sp_type
! Do not edit! This file is automatically generated from the XML Schema
 character(1024)::chemicalSymbol
 real(8)::z
 real(8)::mass
 character(512)::name
  type(muffinTin_type),pointer::muffinTin
  type(atomicState_type_array),pointer::atomicStatearray(:)
  type(basis_type),pointer::basis
end type

type sp_type_array
type(sp_type),pointer::sp
 end type
    
type muffinTin_type
! Do not edit! This file is automatically generated from the XML Schema
 real(8)::rmin
 real(8)::rinf
 real(8)::radius
 integer::radialmeshPoints
end type

type basis_type
! Do not edit! This file is automatically generated from the XML Schema
  type(default_type),pointer::default
  type(custom_type_array),pointer::customarray(:)
  type(lo_type_array),pointer::loarray(:)
end type

type default_type
! Do not edit! This file is automatically generated from the XML Schema
 character(512)::type
 real(8)::trialEnergy
 logical::searchE
  type(wf_type_array),pointer::wfarray(:)
end type

type spdb_type
! Do not edit! This file is automatically generated from the XML Schema
  type(sp_type_array),pointer::sparray(:)
end type

   type(spdb_type)::spdb
contains

function getstructatomicState(thisnode)
! Do not edit! This file is automatically generated from the XML Schema
implicit none
type(Node),pointer::thisnode
type(atomicState_type),pointer::getstructatomicState
type(Node),pointer::np


integer::len=1,i=0
allocate(getstructatomicState)  
#ifdef INPUTDEBUG      
      write(*,*)"we are at atomicState"
#endif
      
nullify(np)  
np=>getAttributeNode(thisnode,"n")
if(associated(np)) then
       call extractDataAttribute(thisnode,"n",getstructatomicState%n)
       call removeAttribute(thisnode,"n")  
        else
        write(*,*)"Parser ERROR: The element 'atomicState' requires the attribute 'n' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"l")
if(associated(np)) then
       call extractDataAttribute(thisnode,"l",getstructatomicState%l)
       call removeAttribute(thisnode,"l")  
        else
        write(*,*)"Parser ERROR: The element 'atomicState' requires the attribute 'l' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"kappa")
if(associated(np)) then
       call extractDataAttribute(thisnode,"kappa",getstructatomicState%kappa)
       call removeAttribute(thisnode,"kappa")  
        else
        write(*,*)"Parser ERROR: The element 'atomicState' requires the attribute 'kappa' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"occ")
if(associated(np)) then
       call extractDataAttribute(thisnode,"occ",getstructatomicState%occ)
       call removeAttribute(thisnode,"occ")  
        else
        write(*,*)"Parser ERROR: The element 'atomicState' requires the attribute 'occ' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"core")
if(associated(np)) then
       call extractDataAttribute(thisnode,"core",getstructatomicState%core)
       call removeAttribute(thisnode,"core")  
        else
        write(*,*)"Parser ERROR: The element 'atomicState' requires the attribute 'core' to be defined."
        write(*,*)"stopped"
        stop
        
endif

      i=0
      len=0
      
end function

function getstructwf(thisnode)
! Do not edit! This file is automatically generated from the XML Schema
implicit none
type(Node),pointer::thisnode
type(wf_type),pointer::getstructwf
type(Node),pointer::np


integer::len=1,i=0
allocate(getstructwf)  
#ifdef INPUTDEBUG      
      write(*,*)"we are at wf"
#endif
      
nullify(np)  
np=>getAttributeNode(thisnode,"trialEnergy")
if(associated(np)) then
       call extractDataAttribute(thisnode,"trialEnergy",getstructwf%trialEnergy)
       call removeAttribute(thisnode,"trialEnergy")  
        else
        write(*,*)"Parser ERROR: The element 'wf' requires the attribute 'trialEnergy' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"matchingOrder")
if(associated(np)) then
       call extractDataAttribute(thisnode,"matchingOrder",getstructwf%matchingOrder)
       call removeAttribute(thisnode,"matchingOrder")  
        else
        write(*,*)"Parser ERROR: The element 'wf' requires the attribute 'matchingOrder' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"searchE")
if(associated(np)) then
       call extractDataAttribute(thisnode,"searchE",getstructwf%searchE)
       call removeAttribute(thisnode,"searchE")  
        else
        write(*,*)"Parser ERROR: The element 'wf' requires the attribute 'searchE' to be defined."
        write(*,*)"stopped"
        stop
        
endif

      i=0
      len=0
      
end function

function getstructcustom(thisnode)
! Do not edit! This file is automatically generated from the XML Schema
implicit none
type(Node),pointer::thisnode
type(custom_type),pointer::getstructcustom
type(Node),pointer::np


integer::len=1,i=0
allocate(getstructcustom)  
#ifdef INPUTDEBUG      
      write(*,*)"we are at custom"
#endif
      
nullify(np)  
np=>getAttributeNode(thisnode,"l")
if(associated(np)) then
       call extractDataAttribute(thisnode,"l",getstructcustom%l)
       call removeAttribute(thisnode,"l")  
        else
        write(*,*)"Parser ERROR: The element 'custom' requires the attribute 'l' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"type")
getstructcustom%type= "apw+lo"
if(associated(np)) then
       call extractDataAttribute(thisnode,"type",getstructcustom%type)
       call removeAttribute(thisnode,"type")  
endif

nullify(np)  
np=>getAttributeNode(thisnode,"trialEnergy")
getstructcustom%trialEnergy=0.15d0
if(associated(np)) then
       call extractDataAttribute(thisnode,"trialEnergy",getstructcustom%trialEnergy)
       call removeAttribute(thisnode,"trialEnergy")  
endif

nullify(np)  
np=>getAttributeNode(thisnode,"searchE")
getstructcustom%searchE=.true.
if(associated(np)) then
       call extractDataAttribute(thisnode,"searchE",getstructcustom%searchE)
       call removeAttribute(thisnode,"searchE")  
endif

            len= countChildEmentsWithName(thisnode,"wf")
     
allocate(getstructcustom%wfarray(len))
Do i=0,len-1
getstructcustom%wfarray(i+1)%wf=>getstructwf(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"wf"),0)) ) 
enddo

      i=0
      len=0
      
end function

function getstructlo(thisnode)
! Do not edit! This file is automatically generated from the XML Schema
implicit none
type(Node),pointer::thisnode
type(lo_type),pointer::getstructlo
type(Node),pointer::np


integer::len=1,i=0
allocate(getstructlo)  
#ifdef INPUTDEBUG      
      write(*,*)"we are at lo"
#endif
      
nullify(np)  
np=>getAttributeNode(thisnode,"l")
if(associated(np)) then
       call extractDataAttribute(thisnode,"l",getstructlo%l)
       call removeAttribute(thisnode,"l")  
        else
        write(*,*)"Parser ERROR: The element 'lo' requires the attribute 'l' to be defined."
        write(*,*)"stopped"
        stop
        
endif

            len= countChildEmentsWithName(thisnode,"wf")

        if(len.eq.0) then
        write(*,*)"Parser ERROR: The lo element must contain at least 1 wf element"
        endif
             
allocate(getstructlo%wfarray(len))
Do i=0,len-1
getstructlo%wfarray(i+1)%wf=>getstructwf(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"wf"),0)) ) 
enddo

      i=0
      len=0
      
end function

function getstructsp(thisnode)
! Do not edit! This file is automatically generated from the XML Schema
implicit none
type(Node),pointer::thisnode
type(sp_type),pointer::getstructsp
type(Node),pointer::np


integer::len=1,i=0
allocate(getstructsp)  
#ifdef INPUTDEBUG      
      write(*,*)"we are at sp"
#endif
      
nullify(np)  
np=>getAttributeNode(thisnode,"chemicalSymbol")
if(associated(np)) then
       call extractDataAttribute(thisnode,"chemicalSymbol",getstructsp%chemicalSymbol)
       call removeAttribute(thisnode,"chemicalSymbol")  
        else
        write(*,*)"Parser ERROR: The element 'sp' requires the attribute 'chemicalSymbol' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"z")
if(associated(np)) then
       call extractDataAttribute(thisnode,"z",getstructsp%z)
       call removeAttribute(thisnode,"z")  
        else
        write(*,*)"Parser ERROR: The element 'sp' requires the attribute 'z' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"mass")
if(associated(np)) then
       call extractDataAttribute(thisnode,"mass",getstructsp%mass)
       call removeAttribute(thisnode,"mass")  
        else
        write(*,*)"Parser ERROR: The element 'sp' requires the attribute 'mass' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"name")
if(associated(np)) then
       call extractDataAttribute(thisnode,"name",getstructsp%name)
       call removeAttribute(thisnode,"name")  
endif

            len= countChildEmentsWithName(thisnode,"muffinTin")

        if(len.eq.0) then
        write(*,*)"Parser ERROR: The sp element must contain at least 1 muffinTin element"
        endif
        getstructsp%muffinTin=>null()
Do i=0,len-1
getstructsp%muffinTin=>getstructmuffinTin(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"muffinTin"),0)) ) 
enddo

            len= countChildEmentsWithName(thisnode,"atomicState")

        if(len.eq.0) then
        write(*,*)"Parser ERROR: The sp element must contain at least 1 atomicState element"
        endif
             
allocate(getstructsp%atomicStatearray(len))
Do i=0,len-1
getstructsp%atomicStatearray(i+1)%atomicState=>getstructatomicState(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"atomicState"),0)) ) 
enddo

            len= countChildEmentsWithName(thisnode,"basis")

        if(len.eq.0) then
        write(*,*)"Parser ERROR: The sp element must contain at least 1 basis element"
        endif
        getstructsp%basis=>null()
Do i=0,len-1
getstructsp%basis=>getstructbasis(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"basis"),0)) ) 
enddo

      i=0
      len=0
      
end function

function getstructmuffinTin(thisnode)
! Do not edit! This file is automatically generated from the XML Schema
implicit none
type(Node),pointer::thisnode
type(muffinTin_type),pointer::getstructmuffinTin
type(Node),pointer::np


integer::len=1,i=0
allocate(getstructmuffinTin)  
#ifdef INPUTDEBUG      
      write(*,*)"we are at muffinTin"
#endif
      
nullify(np)  
np=>getAttributeNode(thisnode,"rmin")
if(associated(np)) then
       call extractDataAttribute(thisnode,"rmin",getstructmuffinTin%rmin)
       call removeAttribute(thisnode,"rmin")  
        else
        write(*,*)"Parser ERROR: The element 'muffinTin' requires the attribute 'rmin' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"rinf")
if(associated(np)) then
       call extractDataAttribute(thisnode,"rinf",getstructmuffinTin%rinf)
       call removeAttribute(thisnode,"rinf")  
        else
        write(*,*)"Parser ERROR: The element 'muffinTin' requires the attribute 'rinf' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"radius")
if(associated(np)) then
       call extractDataAttribute(thisnode,"radius",getstructmuffinTin%radius)
       call removeAttribute(thisnode,"radius")  
        else
        write(*,*)"Parser ERROR: The element 'muffinTin' requires the attribute 'radius' to be defined."
        write(*,*)"stopped"
        stop
        
endif

nullify(np)  
np=>getAttributeNode(thisnode,"radialmeshPoints")
if(associated(np)) then
       call extractDataAttribute(thisnode,"radialmeshPoints",getstructmuffinTin%radialmeshPoints)
       call removeAttribute(thisnode,"radialmeshPoints")  
        else
        write(*,*)"Parser ERROR: The element 'muffinTin' requires the attribute 'radialmeshPoints' to be defined."
        write(*,*)"stopped"
        stop
        
endif

      i=0
      len=0
      
end function

function getstructbasis(thisnode)
! Do not edit! This file is automatically generated from the XML Schema
implicit none
type(Node),pointer::thisnode
type(basis_type),pointer::getstructbasis

integer::len=1,i=0
allocate(getstructbasis)  
#ifdef INPUTDEBUG      
      write(*,*)"we are at basis"
#endif
      
            len= countChildEmentsWithName(thisnode,"default")

        if(len.eq.0) then
        write(*,*)"Parser ERROR: The basis element must contain at least 1 default element"
        endif
        getstructbasis%default=>null()
Do i=0,len-1
getstructbasis%default=>getstructdefault(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"default"),0)) ) 
enddo

            len= countChildEmentsWithName(thisnode,"custom")
     
allocate(getstructbasis%customarray(len))
Do i=0,len-1
getstructbasis%customarray(i+1)%custom=>getstructcustom(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"custom"),0)) ) 
enddo

            len= countChildEmentsWithName(thisnode,"lo")
     
allocate(getstructbasis%loarray(len))
Do i=0,len-1
getstructbasis%loarray(i+1)%lo=>getstructlo(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"lo"),0)) ) 
enddo

      i=0
      len=0
      
end function

function getstructdefault(thisnode)
! Do not edit! This file is automatically generated from the XML Schema
implicit none
type(Node),pointer::thisnode
type(default_type),pointer::getstructdefault
type(Node),pointer::np


integer::len=1,i=0
allocate(getstructdefault)  
#ifdef INPUTDEBUG      
      write(*,*)"we are at default"
#endif
      
nullify(np)  
np=>getAttributeNode(thisnode,"type")
getstructdefault%type= "lapw"
if(associated(np)) then
       call extractDataAttribute(thisnode,"type",getstructdefault%type)
       call removeAttribute(thisnode,"type")  
endif

nullify(np)  
np=>getAttributeNode(thisnode,"trialEnergy")
getstructdefault%trialEnergy=0.15d0
if(associated(np)) then
       call extractDataAttribute(thisnode,"trialEnergy",getstructdefault%trialEnergy)
       call removeAttribute(thisnode,"trialEnergy")  
endif

nullify(np)  
np=>getAttributeNode(thisnode,"searchE")
getstructdefault%searchE=.true.
if(associated(np)) then
       call extractDataAttribute(thisnode,"searchE",getstructdefault%searchE)
       call removeAttribute(thisnode,"searchE")  
endif

            len= countChildEmentsWithName(thisnode,"wf")
     
allocate(getstructdefault%wfarray(len))
Do i=0,len-1
getstructdefault%wfarray(i+1)%wf=>getstructwf(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"wf"),0)) ) 
enddo

      i=0
      len=0
      
end function

function getstructspdb(thisnode)
! Do not edit! This file is automatically generated from the XML Schema
implicit none
type(Node),pointer::thisnode
type(spdb_type),pointer::getstructspdb

integer::len=1,i=0
allocate(getstructspdb)  
#ifdef INPUTDEBUG      
      write(*,*)"we are at spdb"
#endif
      
            len= countChildEmentsWithName(thisnode,"sp")
     
allocate(getstructspdb%sparray(len))
Do i=0,len-1
getstructspdb%sparray(i+1)%sp=>getstructsp(&
removeChild(thisnode,item(getElementsByTagname(thisnode,&
"sp"),0)) ) 
enddo

      i=0
      len=0
      
end function


function countChildEmentsWithName(nodep,name)
  implicit none
  integer::countChildEmentsWithName
  type(Node),pointer ::nodep
  character(len=*),intent(in)::name
  type(NodeList),pointer::children
  type(Node),pointer::child
  
  integer::i
  children=>getChildNodes(nodep)
  countChildEmentsWithName=0
  do i=0,getlength(children)-1
    child=>item(children,i)
    if(name.eq.getNodeName(child)) countChildEmentsWithName=countChildEmentsWithName+1
  end do

end function  
    
end module

