#!/bin/bash
# $Id:  $

if [ -n "$SKIP_CHECK" ]; then
    echo "Skipping checks"
    exit 0
fi

if [ -z "$srcdir" ]; then
  srcdir="./"
fi

datadir=${srcdir:-.}

echo -e "\033[33;1mComparing against reference data\033[0m"
for i in `ls $datadir/*.data | sort`; do
  func=`basename $i .data`
  echo -e "\033[0m :: Testing \033[32;1m$func\033[31;1m"
  $srcdir/xc-reference.pl -f $func
done
echo -e "\033[0m"

#echo -e "\033[33;1mInternal consistency\033[0m"
#for i in `grep -E 'XC_LDA|XC_GGA' $srcdir/../src/xc_funcs.h | awk '{printf("%s,%d\n",$2, $3)}'`; do
#  func=`echo $i|sed 's/,.*//'`;
#  number=`echo $i|sed 's/.*,//'`;
#
#  if [ $number -ne 6 -a $number -ne 160 ]; then
#    echo -e "\033[0m :: Testing \033[32;1m$func\033[0m ($number)"
#    ./xc-consistency $number
#  fi
#  echo
#done
