"""Python script for generating strained structures."""

import os
import pathlib
import numpy as np
from argparse import ArgumentParser
from os.path import join
from typing import Union
from excitingtools import ExcitingInputXML

deformation_map = {
    0: "EEE000",
    1: "E00000",
    2: "0E0000",
    3: "00E000",
    4: "000E00",
    5: "0000E0",
    6: "00000E",
    7: "000EEE",
    8: "EE0000",
    9: "Ee0000",
    10: "EEEEEE",
    11: "E00E00",
    12: "E000E0",
    13: "E0000E",
    14: "EE0E00",
}


def get_deformation_mapping(deformation_code: int) -> str:
    """Returns the deformation code string indicating the type of strains in Voigt notation

    :param deformation_code:
    :return :
    """
    return deformation_map[deformation_code]


def get_langrangian_strain_matrix(eta: float, deformation_str: str) -> np.ndarray:
    """Determines the Langrangian strain matrix based on the deformation string provided

    :param eta: strain value
    :param deformation_str: string determining type deformation
    :return : 3x3 numpy array of langrangian strain matrix
    """
    strain_values = [0, 0, 0, 0, 0, 0]

    for j in range(6):
        if deformation_str[j] == "E":
            strain_values[j] = eta
        elif deformation_str[j] == "e":
            strain_values[j] = -eta

    # Return eta matrix
    return np.array(
        [
            [strain_values[0], strain_values[5] / 2, strain_values[4] / 2],
            [strain_values[5] / 2, strain_values[1], strain_values[3] / 2],
            [strain_values[4] / 2, strain_values[3] / 2, strain_values[2]],
        ]
    )


def get_deformation_matrix(
    eta_matrix: np.ndarray, max_iter=100, tol=1e-10
) -> np.ndarray:
    """Determines the deformation matrix from Langrangian strain matrix

    :param eta_matrix: langrangian strain matrix
    :param max_iter:
    :param tol:
    :return : 3x3 numpy array of deformation matrix
    """
    eps_matrix = eta_matrix

    # Iterative solution to epsilon matrix
    for _ in range(max_iter):
        new_eps_matrix = eta_matrix - 0.5 * np.dot(eps_matrix, eps_matrix)
        if np.linalg.norm(new_eps_matrix - eps_matrix) < tol:
            break
        eps_matrix = new_eps_matrix

    return np.eye(3) + eps_matrix


def setup_deformed_structures(
    input_file: Union[str, pathlib.Path],
    maximum_strain: float,
    number_strain_values: int,
    deformation_code: int,
    workdir=os.getcwd(),
) -> None:
    """Create input files with a series volume values for different strain values.

    :param input_file: Input file.
    :param maximum_strain:
    :param number_strain_values: Number of strain values for which structures are generated by varying the lattice constant.
    :param deformation_code:
    :param workdir: Working directory.
    """
    parsed_input = ExcitingInputXML.from_xml(input_file)

    if maximum_strain == 0:
        with open(join(workdir, "INFO-elastic-constants"), "w") as output_info:
            output_info.write(
                f"\nMaximum Lagrangian strain       =  0\n"
                f"Number of strain values         =  1\n"
                f"Volume of equilibrium unit cell =  1.0 [a.u]^3\n"
                f"Deformation code                =  000000\n"
                f"Deformation label               =  single\n"
            )

        parsed_input.write(join(workdir, "input.xml"))

        # Write strain value to file
        with open(join(workdir, "strain"), "w") as output_str:
            output_str.write(f"0.00")

        print("Single unstrained calculation\n")
        return

    # Extract crystal properties
    if hasattr(parsed_input.structure.crystal_properties, "scale"):
        ref_scale = parsed_input.structure.crystal_properties.scale
    else:
        ref_scale = 1.0

    if hasattr(parsed_input.structure.crystal_properties, "stretch"):
        stretch = parsed_input.structure.crystal_properties.stretch
    else:
        stretch = [1.0, 1.0, 1.0]

    base_vectors = np.array(parsed_input.structure.lattice)

    # Calculate initial volume
    volume = abs(np.linalg.det(base_vectors) * ref_scale**3 * np.prod(stretch))

    # Create work directory
    os.makedirs(workdir, exist_ok=True)

    deformation_str = get_deformation_mapping(deformation_code)

    # Info file
    with open(join(workdir, "INFO-elastic-constants"), "w") as output_info:
        output_info.write(
            f"\nMaximum Lagrangian strain       =  {maximum_strain}\n"
            f"Number of strain values         =  {number_strain_values}\n"
            f"Volume of equilibrium unit cell =  {volume} [a.u]^3\n"
            f"Deformation code                =  {deformation_code}\n"
            f"Deformation label               =  {deformation_str}\n"
        )

    # Calculate strain steps
    delta = number_strain_values - 1
    convert = 1
    if number_strain_values <= 1:
        convert = -1
        delta = 1

    eta_step = 2 * maximum_strain / delta

    for i in range(number_strain_values):
        # Update eta value
        eta = i * eta_step - maximum_strain * convert

        # Create eta matrix
        eta_matrix = get_langrangian_strain_matrix(eta, deformation_str)

        # Calculate deformation matrix
        deformation_matrix = get_deformation_matrix(eta_matrix)

        # Update the base vectors
        new_base_vectors = np.dot(deformation_matrix, base_vectors.T).T

        # Update base vectors in the XML
        parsed_input.structure.lattice = new_base_vectors.tolist()

        # Create rundir
        rundir = join(workdir, f"rundir-{i+1}")
        os.makedirs(rundir, exist_ok=True)

        # Write deformed structure to file
        parsed_input.write(join(rundir, f"input.xml"))

        # Write strain value to file
        with open(join(rundir, f"strain-{i+1}"), "w") as output_str:
            output_str.write(f"{eta:11.8f}")

    parsed_input.write(join(workdir, "source.xml"))


def main() -> None:
    parser = ArgumentParser(
        description="Python script for generating input files for different strain values."
    )

    parser.add_argument(
        "--input-file",
        "-i",
        type=str,
        default=["input.xml"],
        nargs=1,
        dest="infile",
        help="name of the input file",
    )

    parser.add_argument(
        "--root-directory",
        "-r",
        type=str,
        default=[join(os.getcwd(), "workdir")],
        nargs=1,
        dest="workdir",
        help="path for folders that are created by this script",
    )

    parser.add_argument(
        "--maximum-strain",
        "--s-max",
        type=float,
        required=True,
        nargs=1,
        dest="max_strain",
        help="Maximum strain for the fit(smax)",
    )

    parser.add_argument(
        "--number-of-strain-values",
        "-n",
        type=int,
        required=True,
        nargs=1,
        dest="number_strain_values",
        help="The number of strain values in [-smax,smax] having the range [3-99]",
    )

    parser.add_argument(
        "--deformation-code",
        "-d",
        type=int,
        required=True,
        nargs=1,
        dest="deformation_code",
        help="The deformation code in range [0-14] for determining the type of strain",
    )

    args = parser.parse_args()

    infile = join(os.getcwd(), args.infile[0])
    workdir = args.workdir[0]
    maximum_strain = args.max_strain[0]
    number_strain_values = args.number_strain_values[0]
    deformation_code = args.deformation_code[0]

    # Check for input file existence
    if not os.path.exists(infile):
        raise FileNotFoundError(f"Input file not found!")

    # Check smax is in correct range
    if not (0 <= maximum_strain <= 1):
        raise ValueError("Maximum strain value is out of range [0-1]!")

    if not (3 <= number_strain_values <= 99):
        raise ValueError("Number of strain values is out of range [3-99]!")

    # Input the deformation code
    # Display deformation codes and get the deformation code from user input
    print()
    print("------------------------------------------------------------------------")
    print(" List of deformation codes for strains in Voigt notation")
    print("------------------------------------------------------------------------")
    print("  0 =>  ( eta,  eta,  eta,    0,    0,    0)  | volume strain ")
    print("  1 =>  ( eta,    0,    0,    0,    0,    0)  | linear strain along x ")
    print("  2 =>  (   0,  eta,    0,    0,    0,    0)  | linear strain along y ")
    print("  3 =>  (   0,    0,  eta,    0,    0,    0)  | linear strain along z ")
    print("  4 =>  (   0,    0,    0,  eta,    0,    0)  | yz shear strain")
    print("  5 =>  (   0,    0,    0,    0,  eta,    0)  | xz shear strain")
    print("  6 =>  (   0,    0,    0,    0,    0,  eta)  | xy shear strain")
    print("  7 =>  (   0,    0,    0,  eta,  eta,  eta)  | shear strain along (111)")
    print("  8 =>  ( eta,  eta,    0,    0,    0,    0)  | xy in-plane strain ")
    print("  9 =>  ( eta, -eta,    0,    0,    0,    0)  | x(-y) in-plane strain")
    print(" 10 =>  ( eta,  eta,  eta,  eta,  eta,  eta)  | global strain")
    print(" 11 =>  ( eta,    0,    0,  eta,    0,    0)  | mixed strain")
    print(" 12 =>  ( eta,    0,    0,    0,  eta,    0)  | mixed strain")
    print(" 13 =>  ( eta,    0,    0,    0,    0,  eta)  | mixed strain")
    print(" 14 =>  ( eta,  eta,    0,  eta,    0,    0)  | mixed strain")
    print("------------------------------------------------------------------------")

    if not 0 <= deformation_code <= 14:
        raise ValueError("Deformation code is out of range [0-14]!")

    # Set up the deformed structures
    setup_deformed_structures(
        infile, maximum_strain, number_strain_values, deformation_code, workdir
    )


if __name__ == "__main__":
    main()
