!> Coulomb preconditioning helpers used by the potential-mixing residual metric.
module modmixer_coulomb
  use constants, only: fourpi
  use modinput, only: input
  use modmain, only: gc, idxas, igfft, lmmaxvr, natoms, natmtot, ngvec, ngrid, ngrtot, &
 &  nrmt, nrmtmax, nspecies, omega, rmt, sfacg, spnrmax, spr, y00, ylmg, zil
  use m_zfftifc, only: zfftifc
  use precision, only: dp
#ifdef USEOMP
  use omp_lib, only: omp_get_num_threads, omp_get_thread_num
#endif
  implicit none
  private

  public :: potcoulmixer

contains

  !> Compute the Coulomb potential generated by real muffin-tin and interstitial residuals.
  subroutine potcoulmixer(residualmt, residualir, svclmt, svclir)
    implicit none
    !> Real muffin-tin residual in spherical-harmonic representation.
    real(dp), intent(in) :: residualmt(lmmaxvr, nrmtmax, natmtot)
    !> Real interstitial residual on the FFT grid.
    real(dp), intent(in) :: residualir(ngrtot)
    !> Real muffin-tin Coulomb potential in spherical-harmonic representation.
    real(dp), intent(out) :: svclmt(lmmaxvr, nrmtmax, natmtot)
    !> Real interstitial Coulomb potential on the FFT grid.
    real(dp), intent(out) :: svclir(ngrtot)

    integer :: is, ia, ias, ir, lmax
    complex(dp) :: zrho0
    real(dp), allocatable :: jlgr(:, :, :)
    complex(dp), allocatable :: zrhomt(:, :, :)
    complex(dp), allocatable :: zrhoir(:)
    complex(dp), allocatable :: szvclmt(:, :, :)
    complex(dp), allocatable :: szvclir(:)

    allocate(jlgr(0:input%groundstate%lmaxvr + input%groundstate%npsden + 1, ngvec, nspecies))
    allocate(zrhomt(lmmaxvr, nrmtmax, natmtot))
    allocate(zrhoir(ngrtot))
    allocate(szvclmt(lmmaxvr, nrmtmax, natmtot))
    allocate(szvclir(ngrtot))

    do is = 1, nspecies
      do ia = 1, natoms(is)
        ias = idxas(ia, is)
        do ir = 1, nrmt(is)
          call rtozflm(input%groundstate%lmaxvr, residualmt(:, ir, ias), zrhomt(:, ir, ias))
        end do
      end do
    end do

    zrhoir = residualir
    lmax = input%groundstate%lmaxvr + input%groundstate%npsden + 1
    call genjlgpr(lmax, gc, jlgr)
    call zpotcoulmixer(nrmt, nrmtmax, spnrmax, spr, 1, gc, jlgr, ylmg, sfacg, zrhomt, zrhoir, &
 &    szvclmt, szvclir, zrho0)

    do is = 1, nspecies
      do ia = 1, natoms(is)
        ias = idxas(ia, is)
        do ir = 1, nrmt(is)
          call ztorflm(input%groundstate%lmaxvr, szvclmt(:, ir, ias), svclmt(:, ir, ias))
        end do
      end do
    end do

    svclir = real(szvclir, dp)
    deallocate(jlgr, zrhomt, zrhoir, szvclmt, szvclir)
  end subroutine potcoulmixer

  !> Solve the bare Coulomb problem inside a single muffin tin.
  subroutine zpotclmtmixer(lmax, nr, r, ld, zrhomt, zvclmt)
    implicit none
    !> Maximum angular momentum of the spherical-harmonic expansion.
    integer, intent(in) :: lmax
    !> Number of radial mesh points.
    integer, intent(in) :: nr
    !> Radial mesh points for the muffin tin.
    real(dp), intent(in) :: r(nr)
    !> Leading dimension of the spherical-harmonic coefficient arrays.
    integer, intent(in) :: ld
    !> Complex muffin-tin residual in spherical-harmonic representation.
    complex(dp), intent(in) :: zrhomt(ld, nr)
    !> Complex muffin-tin Coulomb potential in spherical-harmonic representation.
    complex(dp), intent(out) :: zvclmt(ld, nr)

    integer :: l, m, lm, ir
    real(dp) :: t1, t2, t3, t4, t5, t6, t7
    real(dp) :: ri(nr), rl(nr), ril1(nr), cf(3, nr)
    real(dp) :: fr1(nr), fr2(nr), fr3(nr), fr4(nr)
    real(dp) :: gr1(nr), gr2(nr), gr3(nr), gr4(nr)

    do ir = 1, nr
      rl(ir) = 1.d0
      ri(ir) = 1.d0 / r(ir)
      ril1(ir) = ri(ir)
    end do

    lm = 0
    do l = 0, lmax
      t1 = fourpi / real(2 * l + 1, dp)
      do m = -l, l
        lm = lm + 1
        do ir = 1, nr
          t2 = rl(ir) * r(ir)**2
          t3 = ril1(ir) * r(ir)**2
          t4 = real(zrhomt(lm, ir), dp)
          t5 = aimag(zrhomt(lm, ir))
          fr1(ir) = t2 * t4
          fr2(ir) = t2 * t5
          fr3(ir) = t3 * t4
          fr4(ir) = t3 * t5
        end do
        call fderiv(-1, nr, r, fr1, gr1, cf)
        call fderiv(-1, nr, r, fr2, gr2, cf)
        call fderiv(-1, nr, r, fr3, gr3, cf)
        call fderiv(-1, nr, r, fr4, gr4, cf)
        t2 = gr3(nr)
        t3 = gr4(nr)
        do ir = 1, nr
          t4 = ril1(ir)
          t5 = rl(ir)
          t6 = t4 * gr1(ir) + t5 * (t2 - gr3(ir))
          t7 = t4 * gr2(ir) + t5 * (t3 - gr4(ir))
          zvclmt(lm, ir) = t1 * cmplx(t6, t7, kind=dp)
        end do
      end do
      if (l .lt. lmax) then
        do ir = 1, nr
          rl(ir) = rl(ir) * r(ir)
          ril1(ir) = ril1(ir) * ri(ir)
        end do
      end if
    end do
  end subroutine zpotclmtmixer

  !> Assemble the bare Coulomb potential from muffin-tin and interstitial residuals.
  subroutine zpotcoulmixer(nr, nrmax, ld, r, igp0, gpc, jlgpr, ylmgp, sfacgp, zrhomt, zrhoir, &
 &    zvclmt, zvclir, zrho0)
    implicit none
    !> Number of radial mesh points for each species.
    integer, intent(in) :: nr(nspecies)
    !> Maximum radial mesh size.
    integer, intent(in) :: nrmax
    !> Leading dimension of the radial mesh array.
    integer, intent(in) :: ld
    !> Species-dependent radial meshes.
    real(dp), intent(in) :: r(ld, nspecies)
    !> Index of the \( G=0 \) vector in the reciprocal grid list.
    integer, intent(in) :: igp0
    !> Reciprocal-grid magnitudes.
    real(dp), intent(in) :: gpc(ngvec)
    !> Spherical Bessel functions \( j_l(G r_{\mathrm{MT}}) \).
    real(dp), intent(in) :: jlgpr(0:input%groundstate%lmaxvr + input%groundstate%npsden + 1, ngvec, nspecies)
    !> Spherical harmonics on reciprocal grid directions.
    complex(dp), intent(in) :: ylmgp(lmmaxvr, ngvec)
    !> Structure factors on the reciprocal grid.
    complex(dp), intent(in) :: sfacgp(ngvec, natmtot)
    !> Complex muffin-tin residual in spherical-harmonic representation.
    complex(dp), intent(in) :: zrhomt(lmmaxvr, nrmax, natmtot)
    !> Complex interstitial residual on the FFT grid.
    complex(dp), intent(in) :: zrhoir(ngrtot)
    !> Complex muffin-tin Coulomb potential in spherical-harmonic representation.
    complex(dp), intent(out) :: zvclmt(lmmaxvr, nrmax, natmtot)
    !> Complex interstitial Coulomb potential on the FFT grid.
    complex(dp), intent(out) :: zvclir(ngrtot)
    !> \( G=0 \) component of the interstitial potential before it is removed.
    complex(dp), intent(out) :: zrho0

    integer :: is, ia, ias, l, m, lm
    integer :: ir, ig, ifg
    real(dp) :: fpo, t1, t2, t3
    complex(dp) :: zsum, zt1, zt2
    real(dp) :: rmtl(0:input%groundstate%lmaxvr + 3, nspecies)
    real(dp) :: rl(nrmax, 0:input%groundstate%lmaxvr)
    complex(dp) :: vilm(lmmaxvr)
    complex(dp) :: qmt(lmmaxvr, natmtot)
    complex(dp) :: qi(lmmaxvr, natmtot)
    complex(dp) :: qilocal(lmmaxvr)
    complex(dp) :: zrp(lmmaxvr)
#ifdef USEOMP
    integer :: ithr, nthreads, whichthread
#endif
    real(dp) :: factnm

    external factnm
    fpo = fourpi / omega

    do is = 1, nspecies
!$OMP PARALLEL DEFAULT(NONE) PRIVATE(ia, ias) &
!$OMP SHARED(input, is, idxas, lmmaxvr, natoms, nr, r, zrhomt, zvclmt)
!$OMP DO
      do ia = 1, natoms(is)
        ias = idxas(ia, is)
        call zpotclmtmixer(input%groundstate%lmaxvr, nr(is), r(:, is), lmmaxvr, zrhomt(:, :, ias), &
 &        zvclmt(:, :, ias))
      end do
!$OMP END DO
!$OMP END PARALLEL
    end do

    do is = 1, nspecies
      rmtl(0, is) = 1.d0
      do l = 1, input%groundstate%lmaxvr + 3
        rmtl(l, is) = rmtl(l - 1, is) * rmt(is)
      end do
    end do

    do is = 1, nspecies
      do ia = 1, natoms(is)
        ias = idxas(ia, is)
        lm = 0
        do l = 0, input%groundstate%lmaxvr
          t1 = real(2 * l + 1, dp) * rmtl(l + 1, is) / fourpi
          do m = -l, l
            lm = lm + 1
            qmt(lm, ias) = t1 * zvclmt(lm, nr(is), ias)
          end do
        end do
      end do
    end do

    zvclir = zrhoir
    call zfftifc(3, ngrid, -1, zvclir)
    qi = 0.d0
    do is = 1, nspecies
      do ia = 1, natoms(is)
        ias = idxas(ia, is)
#ifdef USEOMP
!$OMP PARALLEL DEFAULT(NONE) PRIVATE(qilocal,ig,ifg,zt1,t1,lm,t2,zt2,m,l,nthreads,whichthread,ithr) &
!$OMP SHARED(input,gpc,sfacgp,zvclir,rmt,qi,ias,ngvec,is,ylmgp,jlgpr,zil,rmtl,igfft)
        qilocal = 0.d0
!$OMP DO
#else
        qilocal = 0.d0
#endif
        do ig = 1, ngvec
          ifg = igfft(ig)
          if (gpc(ig) .gt. input%structure%epslat) then
            zt1 = fourpi * zvclir(ifg) * sfacgp(ig, ias)
            t1 = 1.d0 / (gpc(ig) * rmt(is))
            lm = 0
            do l = 0, input%groundstate%lmaxvr
              t2 = t1 * rmtl(l + 3, is) * jlgpr(l + 1, ig, is)
              zt2 = t2 * zt1 * zil(l)
              do m = -l, l
                lm = lm + 1
                qilocal(lm) = qilocal(lm) + zt2 * conjg(ylmgp(lm, ig))
              end do
            end do
          else
            t1 = fourpi * y00 * rmtl(3, is) / 3.d0
            qilocal(1) = qilocal(1) + t1 * zvclir(ifg)
          end if
        end do
#ifdef USEOMP
!$OMP END DO
        nthreads = omp_get_num_threads()
        whichthread = omp_get_thread_num()
        do ithr = 0, nthreads - 1
          if (ithr .eq. whichthread) qi(:, ias) = qi(:, ias) + qilocal(:)
!$OMP BARRIER
        end do
!$OMP END PARALLEL
#else
        qi(:, ias) = qi(:, ias) + qilocal(:)
#endif
      end do
    end do

    do is = 1, nspecies
      do ia = 1, natoms(is)
        ias = idxas(ia, is)
        lm = 0
        do l = 0, input%groundstate%lmaxvr
          t1 = factnm(2 * (l + input%groundstate%npsden) + 3, 2) / factnm(2 * l + 1, 2)
          do m = -l, l
            lm = lm + 1
            zrp(lm) = (qmt(lm, ias) - qi(lm, ias)) * t1
          end do
        end do
#ifdef USEOMP
!$OMP PARALLEL DEFAULT(NONE) PRIVATE(ig,ifg,zt1,t1,t2,zsum,m,l,lm,t3) &
!$OMP SHARED(input,gpc,zvclir,rmt,ias,ngvec,is,ylmgp,jlgpr,zil,rmtl,igfft,zrp,fpo,sfacgp)
!$OMP DO
#endif
        do ig = 1, ngvec
          ifg = igfft(ig)
          if (gpc(ig) .gt. input%structure%epslat) then
            zt1 = fpo * conjg(sfacgp(ig, ias))
            t1 = gpc(ig) * rmt(is)
            t2 = t1**(input%groundstate%npsden + 1)
            lm = 0
            do l = 0, input%groundstate%lmaxvr
              lm = lm + 1
              zsum = zrp(lm) * ylmgp(lm, ig)
              do m = -l + 1, l
                lm = lm + 1
                zsum = zsum + zrp(lm) * ylmgp(lm, ig)
              end do
              t3 = jlgpr(input%groundstate%npsden + l + 1, ig, is) / (t2 * rmtl(l, is))
              zvclir(ifg) = zvclir(ifg) + t3 * zt1 * zsum * conjg(zil(l))
            end do
          else
            t1 = fpo * y00 / factnm(2 * input%groundstate%npsden + 3, 2)
            zvclir(ifg) = zvclir(ifg) + t1 * zrp(1)
          end if
        end do
#ifdef USEOMP
!$OMP END DO
!$OMP END PARALLEL
#endif
      end do
    end do

    ifg = igfft(igp0)
    zrho0 = zvclir(ifg)
    zvclir(ifg) = 0.d0
    do ig = 1, ngvec
      ifg = igfft(ig)
      if (gpc(ig) .gt. input%structure%epslat) then
        zvclir(ifg) = fourpi * zvclir(ifg) / (gpc(ig)**2)
      else
        zvclir(ifg) = 0.d0
      end if
    end do

    do is = 1, nspecies
      do ir = 1, nr(is)
        t1 = r(ir, is) / rmt(is)
        rl(ir, 0) = 1.d0
        do l = 1, input%groundstate%lmaxvr
          rl(ir, l) = rl(ir, l - 1) * t1
        end do
      end do
      do ia = 1, natoms(is)
        ias = idxas(ia, is)
        vilm = 0.d0
#ifdef USEOMP
!$OMP PARALLEL DEFAULT(NONE) PRIVATE(ig,ifg,zt1,zt2,m,l,lm,qilocal,nthreads,whichthread,ithr) &
!$OMP SHARED(input,zvclir,ias,ngvec,is,ylmgp,jlgpr,zil,igfft,sfacgp,vilm)
        qilocal = 0.d0
!$OMP DO
#else
        qilocal = 0.d0
#endif
        do ig = 1, ngvec
          ifg = igfft(ig)
          zt1 = fourpi * zvclir(ifg) * sfacgp(ig, ias)
          lm = 0
          do l = 0, input%groundstate%lmaxvr
            zt2 = jlgpr(l, ig, is) * zt1 * zil(l)
            do m = -l, l
              lm = lm + 1
              qilocal(lm) = qilocal(lm) + zt2 * conjg(ylmgp(lm, ig))
            end do
          end do
        end do
#ifdef USEOMP
!$OMP END DO
        nthreads = omp_get_num_threads()
        whichthread = omp_get_thread_num()
        do ithr = 0, nthreads - 1
          if (ithr .eq. whichthread) vilm = vilm + qilocal
!$OMP BARRIER
        end do
!$OMP END PARALLEL
#else
        vilm = vilm + qilocal
#endif

        lm = 0
        do l = 0, input%groundstate%lmaxvr
          do m = -l, l
            lm = lm + 1
            zt1 = vilm(lm) - zvclmt(lm, nr(is), ias)
            do ir = 1, nr(is)
              zvclmt(lm, ir, ias) = zvclmt(lm, ir, ias) + zt1 * rl(ir, l)
            end do
          end do
        end do
      end do
    end do

    call zfftifc(3, ngrid, 1, zvclir)
  end subroutine zpotcoulmixer

end module modmixer_coulomb
