
! Copyright (C) 2002-2010 J. K. Dewhurst, S. Sharma, C. Meisenbichler and
! C. Ambrosch-Draxl.
! This file is distributed under the terms of the GNU General Public License.
! See the file COPYING for license details.

!
!
#include "maxdefinitions.inc"
Module mod_misc
      Use modinput
!---------------------------------!
!     miscellaneous variables     !
!---------------------------------!
! code version
      Integer :: version (3)
! reference version for LDA+U
      integer, parameter :: refversion_ldapu(3) = (/ 0, 9, 131 /)
! reference version for new exciting
      integer, parameter :: refversion_new(3) = (/ 0, 9, 224 /)
! reference version (date-based) for githash in STATE.OUT file
      integer, parameter :: refversion_gitstate(3) = (/ 10, 4, 14 /)
! git hash value
      character(40) :: githash
! maximum number of tasks
      Integer, Parameter :: maxtasks = 40
! number of tasks
      Integer :: ntasks
! task array
      Integer :: tasks (maxtasks)
! current task
      Integer :: task
! tstop is .true. if STOP file exists
      Logical :: tstop
! tlast is .true. if self-consistent loop is on the last iteration
      Logical :: tlast
! number of iterations after which STATE.OUT is written
!replaced by inputstructureinteger::nwrite
! filename extension for files generated by gndstate
      Character (256) :: filext
! default file extension
      Data filext / '.OUT' /
! scratch space path
      Character (256) :: scrpath
! maximum number of note lines
      Integer, Parameter :: maxnlns = 20
! number of note lines
      Integer :: notelns
! notes to include in INFO.OUT
      Character (80) :: notes (maxnlns)
!
End Module
!
