
module mod_xsf_format
	use modinput
	use modmain, only : natmtot, nspecies, natoms, atposc
	implicit none

	real(8), parameter :: bohr2ang = 0.529177d0
	private bohr2ang

contains

!-------------------------------------------------------------------------------
	subroutine write_structure_xsf(fname)
  	implicit none
  	! input/output
  	character(*), intent(in) :: fname
  	! local
  	integer :: is, ia
  	open(80,file=trim(fname),status='Unknown',action='Write')
  	write(80,*) 'CRYSTAL'
  	write(80,*) 'PRIMVEC'
  	write(80,*) input%structure%crystal%basevect(:,1)*bohr2ang
  	write(80,*) input%structure%crystal%basevect(:,2)*bohr2ang
  	write(80,*) input%structure%crystal%basevect(:,3)*bohr2ang
  	write(80,*) 'PRIMCOORD'
  	write(80,*) natmtot, ' 1'
  	do is = 1, nspecies
  	do ia = 1, natoms(is)
    	write(80,'(A2,3F14.8)') &
      &  trim(input%structure%speciesarray(is)%species%chemicalSymbol), &
      &  atposc(:,ia,is)*bohr2ang
  	end do
  	end do
  	write(80,*)
  	close(80)
  	return
	end subroutine

  !-------------------------------------------------------------------------------
  subroutine write_2d_xsf(fname,npt,rdata)
  	implicit none
  	! input/output
  	character(*) :: fname
  	integer, intent(in) :: npt
  	real(8), intent(in) :: rdata(npt)
  	! local
  	integer :: ip, i, is, ia
  	real(8) :: boxl(3,3), boxc(3,3)
  	character(30) :: frmt
  
  	type(plot2d_type), pointer :: plotdef
    plotdef => input%properties%wfplot%plot2d
  
    boxl(1,:) = plotdef%parallelogram%origin%coord
    boxl(2,:) = plotdef%parallelogram%pointarray(1)%point%coord-boxl(1,:)
    boxl(3,:) = plotdef%parallelogram%pointarray(2)%point%coord-boxl(1,:)
    do i = 1, 3
      call r3mv(input%structure%crystal%basevect, boxl(i,:), boxc(i,:))
    end do
  
    call write_structure_xsf(fname)

  	open(80,file=trim(fname),status='Unknown',action='Write',access='Append')
  	write(80,*) 'BEGIN_BLOCK_DATAGRID_2D'
  	write(80,*) 'Generated by mod_xsf_format'
  	write(80,*) 'BEGIN_DATAGRID_2D'
  	write(80,*) plotdef%parallelogram%grid(1)+1, &
  	&						plotdef%parallelogram%grid(1)+1
  	write(80,*) boxc(1,:)*bohr2ang
  	write(80,*) boxc(2,:)*bohr2ang
  	write(80,*) boxc(3,:)*bohr2ang
  	frmt = "(8e20.10)"
    write(80,trim(frmt)) rdata
    write(80,*) 'END_DATAGRID_2D'
    write(80,*) 'END_BLOCK_DATAGRID_2D'
  	close(80)
  
  	return
  end subroutine

  !-------------------------------------------------------------------------------
  subroutine write_3d_xsf(fname,npt,rdata)
  	implicit none
  	! input/output
  	character(*) :: fname
  	integer, intent(in) :: npt
  	real(8), intent(in) :: rdata(npt)
  	! local
  	integer :: ip, i, is, ia
  	real(8) :: boxl(4,3), boxc(4,3)
  	character(30) :: frmt
  
  	type(plot3d_type), pointer :: plotdef
    plotdef => input%properties%wfplot%plot3d
  
    boxl(1,:) = plotdef%box%origin%coord
    boxl(2,:) = plotdef%box%pointarray(1)%point%coord-boxl(1,:)
    boxl(3,:) = plotdef%box%pointarray(2)%point%coord-boxl(1,:)
    boxl(4,:) = plotdef%box%pointarray(3)%point%coord-boxl(1,:)
    do i = 1, 4
      call r3mv(input%structure%crystal%basevect, boxl(i,:), boxc(i,:))
    end do

    call write_structure_xsf(fname)
  
  	open(80,file=trim(fname),status='Unknown',action='Write',access='Append')
  	write(80,*) 'BEGIN_BLOCK_DATAGRID_3D'
  	write(80,*) 'Generated by mod_xsf_format'
  	write(80,*) 'BEGIN_DATAGRID_3D'
  	write(80,*) plotdef%box%grid(1)+1, &
  	&						plotdef%box%grid(2)+1, &
  	&						plotdef%box%grid(3)+1
  	write(80,*) boxc(1,:)*bohr2ang
  	write(80,*) boxc(2,:)*bohr2ang
  	write(80,*) boxc(3,:)*bohr2ang
  	write(80,*) boxc(4,:)*bohr2ang
  	frmt = "(8e20.10)"
    write(80,trim(frmt)) rdata
    write(80,*) 'END_DATAGRID_3D'
    write(80,*) 'END_BLOCK_DATAGRID_3D'
  	close(80)
  
  	return
  end subroutine	
  
end module