"""Run a series of **exciting** calculations for structures with different volumes.

Located at `excitingscripts/execute/volume_optimization.py`.

Call as:

```bash
python3 -m excitingscripts.execute.volume_optimization nr_vol
```
Where <code>nr_vol</code> is the number of volume values for which structures are generated by varying the lattice constant.
"""

import os
from argparse import ArgumentParser
from os.path import join

import numpy as np
from excitingscripts.execute.single import run_exciting
from excitingtools import parse


def execute_volume_optimization(
    number_volume_values: int,
    root_directory=os.getcwd(),
    excitingroot=os.getenv("EXCITINGROOT"),
) -> np.ndarray:
    """Execute a series of exciting calculations with different volumes obtained by varying the lattice constant.

    :param number_volume_values: Number of volume values for which structures are generated by varying the lattice constant.
    :param root_directory: Root directory.
    :param excitingroot: Environment variable string.
    :returns: NumPy array containing total energy values and corresponding volume values.
    """
    total_energy = []
    volume_values = []

    for i_v in range(0, number_volume_values):
        run_dir = join(root_directory, f"volume-{i_v + 1}")
        infofile = join(run_dir, "INFO.OUT")

        run_exciting(run_dir, excitingroot)

        results = parse(infofile)
        max_scf = max([int(i) for i in results["scl"].keys()])
        converged_results = results["scl"][str(max_scf)]
        total_energy.append(converged_results["Total energy"])
        volume_values.append(results["initialization"]["Unit cell volume"])

    energy_volume_data = np.vstack((volume_values, total_energy)).T

    return energy_volume_data


def main() -> None:
    parser = ArgumentParser(
        description="""Execute a series of exciting calculations with different volumes obtained by varying the lattice constant."""
    )

    parser.add_argument(
        "number_volume_values",
        type=int,
        nargs=1,
        help="number of volume values for which structures are generated",
    )

    parser.add_argument(
        "--root-directory",
        "-r",
        type=str,
        default=[os.getcwd()],
        nargs=1,
        dest="root_directory",
        help="root path for files that are created by this script",
    )

    args = parser.parse_args()

    energy_volume_data = execute_volume_optimization(
        number_volume_values=args.number_volume_values[0],
        root_directory=args.root_directory[0],
    )

    with open(f"{args.root_directory[0]}/energy-vs-volume", "w") as f:
        np.savetxt(f, energy_volume_data)


if __name__ == "__main__":
    main()
