#!/bin/csh
if ( ! -d cv ) then
  mkdir cv
endif

cp lat.in cv/
echo -n "" >! cv/energy.in
echo -n "" >! cv/str.in
echo -n "" >! cv/strname.in
foreach dir (`ls -1 */energy | sed 's+/energy++g' | sort -n`)
  if ( ! -e $dir/error ) then
    echo $dir
    echo $dir >>! cv/strname.in
    if ( -e $dir/energy ) then 
      echo `cat $dir/energy` `tail +2 $dir/str.out | awk '{print $4}' | wc -w` | awk '{printf("%.10g\n",$1/$2)}' >>! cv/energy.in
    else
      echo x >! cv/energy.in
    endif
    cat $dir/str.out >>! cv/str.in
    (echo "end"; echo "") >>! cv/str.in
  endif
end
