#!/bin/csh
awk 'BEGIN {pat="for ("; p=1; b=0; toadd=0;} \
{ \
  for (c=1; c<=length($0); c++) { \
    ch=substr($0,c,1); \
    if (ch=="{") { \
      bracket[b]=toadd; b++; \
      toadd=0; \
      printf ch; \
    } \
    else if (ch=="}") { \
      b--; \
      if (bracket[b]==1) {printf "}";} \
      printf ch; \
    } \
    else if (ch==substr(pat,p,1)) { \
      p++; \
      if (p>length(pat)) { \
	printf "{" pat; \
        toadd=1; \
        p=1; \
      } \
    } \
    else { \
      if (p>1) { \
	printf substr(pat,1,p-1); \
        p=1; \
      } \
      printf ch; \
    } \
  } \
  print substr(pat,1,p-1); p=1;\
}'
