#! /bin/sh

echo
echo "Running test..."
echo

\cp -f exciting.in_ exciting.in

../../bin/excitingser

\rm -fr _current
\mkdir _current
\cp -f *.in *.OUT fort.* _current
diff -r -B -w _reference _current > reference_current.diff

echo "done."
echo
